project:
  type: book
  output-dir: _book
  preview:
    port: 5896
    browser: true
  render:
    - "*.qmd"
  resources:
    - "data/"
    - "images/"
    - "figs/"

book:
  title: "Programming for Analytics in R"
  reader-mode: true
  author: "John Paul Helveston"
  date: "12/19/2022"

  page-footer:
    left: |
      Programming for Analytics in R was written by John Paul Helveston
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.png
  favicon: cover.png

  site-url: https://p4a.jhelvy.com/
  repo-url: https://github.com/jhelvy/p4a/
  repo-branch: main
  repo-actions: [edit, issue]

  sidebar:
    search: true
    style: docked
    
  chapters:
    - index.qmd
    - intro.qmd

    - part: programming.qmd
      chapters:
        - getting-started.qmd
        - operators-data-types.qmd
        - functions-packages.qmd
        - creating-functions.qmd
        - conditionals.qmd
        - testing-debugging.qmd
        - iteration.qmd
        - vectors.qmd
        - strings.qmd

    - part: data-analysis.qmd
      chapters:
        - data-frames.qmd
        - data-wrangling.qmd
        - data-visualization.qmd

    - part: extensions.qmd
      chapters:
        - monte-carlo-methods.qmd
        - python-in-r.qmd

format:
  html:
    theme: cosmo
    code-link: true
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: false
    author-meta: "John Paul Helveston"
    callout-appearance: simple
